version: '2'
volumes:
    shared-data:
services:
    controller:
      restart: always
      privileged: true
      build: .
      volumes:
        - 'shared-data:/data/my_data'
      ports:
        - '8080:5000'
      extra_hosts:
        - "host.docker.internal:host-gateway"
